import re
import os

# Pattern for Qt includes
QT_PATTERN = re.compile(r'^#include\s*[<\"](Q[^>\"]+|wobject[^>\"]+)[>\"]')

# All files to process
files = [
    'Artifact/include/Mask/MaskPath.ixx',
    'Artifact/include/Generator/DistributionModes.ixx',
    'Artifact/include/Controller/TimelineViewProvider.ixx',
    'Artifact/include/Audio/ArtifactAudioWaveform.ixx',
    'Artifact/include/Application/ArtifactApplicationManager.ixx',
    'Artifact/include/Generator/CloneGenerator.ixx',
    'Artifact/include/Script/ArtifactPythonHookManager.ixx',
    'Artifact/include/Audio/ArtifactAudioMixer.ixx',
    'Artifact/include/Generator/ArtifactParticleGenerator.ixx',
    'Artifact/include/Generator/AbstractGeneratorEffector.ixx',
    'Artifact/include/Application/ActiveContextService.ixx',
    'Artifact/include/Project/ArtifactProjectImporter.ixx',
    'Artifact/include/Service/ArtifactClipboardService.ixx',
    'Artifact/include/Project/TreeFilterProxyModel.ixx',
    'Artifact/include/Project/ArtifactProjectHealthChecker.ixx',
    'Artifact/include/Project/ArtifactProjectStatistics.ixx',
    'Artifact/include/Project/ArtifactPresetManager.ixx',
    'Artifact/include/Audio/Effects/ArtifactAudioOutput.ixx',
    'Artifact/include/Service/ArtifactToolService.ixx',
    'Artifact/include/Project/ArtifactProjectExporter.ixx',
    'Artifact/include/Project/ArtifactProjectSetting.ixx',
    'Artifact/include/Asset/AssetMenuModel.ixx',
    'Artifact/include/Project/ArtifactAutoSaveManager.ixx',
    'Artifact/include/Project/ArtifactProjectCleanupTool.ixx',
    'Artifact/include/Asset/AssetDirectoryModel.ixx',
    'Artifact/include/Audio/Effects/ArtifactAudioEffectBase.ixx',
    'Artifact/include/LOD/ArtifactLODManager.ixx',
    'Artifact/include/Project/ArtifactProjectManager.ixx',
    'Artifact/include/Service/ArtifactPlaybackShortcuts.ixx',
    'Artifact/include/Composition/ArtifactCompositionInitParams.ixx',
    'Artifact/include/Project/ArtifactProjectItems.ixx',
    'Artifact/include/Composition/ArtifactComposition3D.ixx',
    'Artifact/include/Project/ArtifactProjectInitParams.ixx',
    'Artifact/include/Service/ArtifactEffectService.ixx',
    'Artifact/include/Project/ArtifactProjectModel.ixx',
    'Artifact/include/Composition/MetadataVectorizer.ixx',
    'Artifact/include/Project/ArtifactProjectPackager.ixx',
    'Artifact/include/Preview/ArtifactTimelineClock.ixx',
    'Artifact/include/Render/ArtifactIRenderer.ixx',
    'Artifact/include/Preview/ArtifactPreviewController.ixx',
    'Artifact/include/Composition/CompositionSettings.ixx',
    'Artifact/include/Render/ArtifactPerformanceMonitor.ixx',
    'Artifact/include/Event/ArtifactEventTypes.ixx',
    'Artifact/include/Composition/ArtifactFindCompositionQuery.ixx',
    'Artifact/include/Render/ArtifactRenderManager.ixx',
    'Artifact/include/Proxy/ProxyService.ixx',
    'Artifact/include/Composition/ArtifactCompositionResult.ixx',
    'Artifact/include/Color/ColorPaletteManager.ixx',
    'Artifact/include/Color/ArtifactColorWheels.ixx',
    'Artifact/include/Tool/Tool.ixx',
    'Artifact/include/Color/ArtifactColorSettings.ixx',
    'Artifact/include/Timeline/ArtifactTimelineIconModel.ixx',
    'Artifact/include/Translation/TranslationManager.ixx',
    'Artifact/include/Color/ArtifactColorScienceManager.ixx',
    'Artifact/include/Color/ArtifactColorNodeGraph.ixx',
    'Artifact/include/Color/ArtifactColorNode.ixx',
    'Artifact/include/Render/ArtifactRenderROI.ixx',
    'Artifact/include/Effect/ArtifactTransition.ixx',
    'Artifact/include/Render/DiligentDeviceManager.ixx',
    'Artifact/include/Engine/DAG/Port.ixx',
    'Artifact/include/Color/ArtifactColorManagement.ixx',
    'Artifact/include/Engine/DAG/Node.ixx',
    'Artifact/include/Engine/DAG/LayerGraphBuilder.ixx',
    'Artifact/include/Engine/DAG/Graph.ixx',
    'Artifact/include/Engine/DAG/CompositionGraphBuilder.ixx',
    'Artifact/include/Engine/DAG/Executor.ixx',
    'Artifact/include/Engine/DAG/CompositionGraph.ixx',
    'Artifact/include/Core/SystemStats.ixx',
    'Artifact/include/Engine/DAG/Connection.ixx',
    'Artifact/include/Layer/ArtifactCameraLayer.ixx',
    'Artifact/include/Layer/ArtifactLayerMatte.ixx',
    'Artifact/include/Effetcs/ArtifactAbstractEffect.ixx',
    'Artifact/include/Effetcs/ArtifactCornerPinEffect.ixx',
    'Artifact/include/Effetcs/AutoMosaicEffect.ixx',
    'Artifact/include/Layer/ArtifactLayerInitParams.ixx',
    'Artifact/include/Layer/ArtifactLayerFactory.ixx',
    'Artifact/include/Effetcs/ArtifactGlobalEffectManager.ixx',
    'Artifact/include/Effetcs/Clone/CloneCore.ixx',
    'Artifact/include/Effetcs/DirectionalGlowEffect.ixx',
    'Artifact/include/Effetcs/Blur/BlurEffect.ixx',
    'Artifact/include/Layer/ArtifactHierarchyModel.ixx',
    'Artifact/include/Effetcs/ColorCorrection/BrightnessEffect.ixx',
    'Artifact/include/Effetcs/Clone/BasicEffectors.ixx',
    'Artifact/include/Effetcs/LayerTransform/LayerTransform2D.ixx',
    'Artifact/include/Layer/ArtifactLightLayer.ixx',
    'Artifact/include/Effetcs/Clone/AdvancedEffectors.ixx',
    'Artifact/include/Effetcs/Field/BoxField.ixx',
    'Artifact/include/Layer/ArtifactVideoLayer.ixx',
    'Artifact/include/Effetcs/Generator/FractalNoiseGenerator.ixx',
    'Artifact/include/Effetcs/LiftGammaGainEffect.ixx',
    'Artifact/include/Layer/ArtifactTextLayer.ixx',
    'Artifact/include/Effetcs/Transform/TwistTransform.ixx',
    'Artifact/include/Effetcs/Field/LinearField.ixx',
    'Artifact/include/Effetcs/Render/PBRMaterialEffect.ixx',
    'Artifact/include/Effetcs/Rasterizer/DropShadowEffect.ixx',
    'Artifact/include/Effetcs/Generator/ClonerGenerator.ixx',
    'Artifact/include/Effetcs/Transform/BendTransform.ixx',
    'Artifact/include/Effetcs/Field/SphericalField.ixx',
    'Artifact/include/Effetcs/Field/RadialField.ixx',
    'Artifact/include/Effetcs/ColorCorrection/ExposureEffect.ixx',
    'Artifact/include/Layer/ArtifactSvgLayer.ixx',
    'Artifact/include/Layer/ArtifactSolidImageLayer.ixx',
    'Artifact/include/Effetcs/ColorCorrection/HueAndSaturation.ixx',
    'Artifact/include/Layer/ArtifactParticleLayer.ixx',
    'Artifact/include/GUI/WindowPluginManager.ixx',
    'Artifact/include/Render/Software/ArtifactSoftwareImageCompositor.ixx',
    'ArtifactCore/include/Composition/PreCompose.ixx',
    'ArtifactCore/include/Common/Size.ixx',
    'ArtifactCore/include/Codec/MFFrameExtractor.ixx',
    'ArtifactCore/include/Composition/CompositionBuffer2D.ixx',
    'ArtifactCore/include/Common/OperationgSystem.ixx',
    'ArtifactCore/include/Codec/MFEncoder.ixx',
    'ArtifactCore/include/Codec/FFmpegThumbnailExtractor.ixx',
    'ArtifactCore/include/Codec/FFMpegAudioDecoder.ixx',
    'ArtifactCore/include/Codec/DecoderPoolManager.ixx',
    'ArtifactCore/include/Command/CommonCommands.ixx',
    'ArtifactCore/include/Command/EditSessionManager.ixx',
    'ArtifactCore/include/Clipboard/ClipboardManager.ixx',
    'ArtifactCore/include/Command/SerializableCommand.ixx',
    'ArtifactCore/include/Command/EditSession.ixx',
    'ArtifactCore/include/Analyze/SmartPaletteAnalyzer.ixx',
    'ArtifactCore/include/Command/LambdaCommand.ixx',
    'ArtifactCore/include/Color/ColorHarmonizer.ixx',
    'ArtifactCore/include/Diagnostics/Logger.ixx',
    'ArtifactCore/include/EnvironmentVariable/EnvironmentVariable.ixx',
    'ArtifactCore/include/File/FileTypeDetector.ixx',
    'ArtifactCore/include/Diagnostics/CrashHandler.ixx',
    'ArtifactCore/include/File/FileInfo.ixx',
    'ArtifactCore/include/Frame/FramePosition.ixx',
    'ArtifactCore/include/Frame/FrameRate.ixx',
    'ArtifactCore/include/Frame/FrameRange.ixx',
    'ArtifactCore/include/Font/FontDescriptor.ixx',
    'ArtifactCore/include/AI/AIActionContext.ixx',
    'ArtifactCore/include/AI/AIContext.ixx',
    'ArtifactCore/include/Font/FreeFont.ixx',
    'ArtifactCore/include/AI/AIToolExecutor.ixx',
    'ArtifactCore/include/AI/AIPromptGenerator.ixx',
    'ArtifactCore/include/Core/UniformScale.ixx',
    'ArtifactCore/include/Color/ColorLUT.ixx',
    'ArtifactCore/include/Rig/Rig2D.ixx',
    'ArtifactCore/include/AI/LlamaLocalAgent.ixx',
    'ArtifactCore/include/Color/ColorSpace.ixx',
    'ArtifactCore/include/RenderWorker.ixx',
    'ArtifactCore/include/AI/IDescribable.ixx',
    'ArtifactCore/include/Core/ShapePath.ixx',
    'ArtifactCore/include/Physics/FractureEngine.ixx',
    'ArtifactCore/include/AI/TieredAIManager.ixx',
    'ArtifactCore/include/Core/Position2D.ixx',
    'ArtifactCore/include/AI/OnnxDmlLocalAgent.ixx',
    'ArtifactCore/include/Core/Point2D.ixx',
    'ArtifactCore/include/AI/ObjectDetector.ixx',
    'ArtifactCore/include/AI/LocalAIAgent.ixx',
    'ArtifactCore/include/Core/KeyFrame.ixx',
    'ArtifactCore/include/Property/AbstractProperty.ixx',
    'ArtifactCore/include/Core/FastSettingsStore.ixx',
    'ArtifactCore/include/Property/PropertyGroup.ixx',
    'ArtifactCore/include/Physics/2D/Physics2D.ixx',
    'ArtifactCore/include/Property/Property.ixx',
    'ArtifactCore/include/Property/PropertyTypes.ixx',
    'ArtifactCore/include/Property/PropertyLinkManager.ixx',
    'ArtifactCore/include/Core/AspectRatio.ixx',
    'ArtifactCore/include/Audio/SimpleWav.ixx',
    'ArtifactCore/include/Render/RenderStatics.ixx',
    'ArtifactCore/include/Platform/ShellUtils.ixx',
    'ArtifactCore/include/Render/RendererQueueManager.ixx',
    'ArtifactCore/include/Preview/PreviewQuality.ixx',
    'ArtifactCore/include/Color/Grading/LUTLoader.ixx',
    'ArtifactCore/include/Color/Grading/ColorScopes.ixx',
    'ArtifactCore/include/Reactive/ReactiveEvents.ixx',
    'ArtifactCore/include/Render/RenderSettings.ixx',
    'ArtifactCore/include/Color/Grading/ColorCurves.ixx',
    'ArtifactCore/include/Render/RendererQueueSetting.ixx',
    'ArtifactCore/include/Container/MultiIndexContainer.ixx',
    'ArtifactCore/include/Video/AbstractEncoder.ixx',
    'ArtifactCore/include/Video/FFmpegAudioEncoder.ixx',
    'ArtifactCore/include/Audio/AudioWriter.ixx',
    'ArtifactCore/include/Audio/AudioFrame.ixx',
    'ArtifactCore/include/Video/AbstractDecoder.ixx',
    'ArtifactCore/include/Mesh/Mesh.ixx',
    'ArtifactCore/include/Playback/PlaybackState.ixx',
    'ArtifactCore/include/Video/EncoderSetting.ixx',
    'ArtifactCore/include/Audio/AudioSegment.ixx',
    'ArtifactCore/include/Audio/AudioRingBuffer.ixx',
    'ArtifactCore/include/IO/Image/SearchImage.ixx',
    'ArtifactCore/include/Playback/PlaybackClock.ixx',
    'ArtifactCore/include/Video/Stabilizer.ixx',
    'ArtifactCore/include/Audio/AudioRenderer.ixx',
    'ArtifactCore/include/Video/PlaybackManager.ixx',
    'ArtifactCore/include/Audio/AudioRasterizer.ixx',
    'ArtifactCore/include/Video/FFMpegVideoDecoder.ixx',
    'ArtifactCore/include/Audio/AudioCache.ixx',
    'ArtifactCore/include/Video/FFMpegEncoder.ixx',
    'ArtifactCore/include/Audio/AudioPanner.ixx',
    'ArtifactCore/include/Time/TimeRemap.ixx',
    'ArtifactCore/include/Text/TextStyle.ixx',
    'ArtifactCore/include/Audio/AudioBufferQueue.ixx',
    'ArtifactCore/include/IO/Image/ImageImporter.ixx',
    'ArtifactCore/include/Audio/AudioModule.ixx',
    'ArtifactCore/include/Text/TextAnimator.ixx',
    'ArtifactCore/include/Audio/AudioBackend.ixx',
    'ArtifactCore/include/Audio/AudioFrameToQAudioFormatConverter.ixx',
    'ArtifactCore/include/Time/TimeCode.ixx',
    'ArtifactCore/include/Text/GlyphLayout.ixx',
    'ArtifactCore/include/IO/Image/ImageExporterStb.ixx',
    'ArtifactCore/include/Time/RationalTime.ixx',
    'ArtifactCore/include/Graphics/GPUTextureCacheManager.ixx',
    'ArtifactCore/include/Time/Duration.ixx',
    'ArtifactCore/include/Graphics/ShaderCreationHelper.ixx',
    'ArtifactCore/include/Media/MediaSource.ixx',
    'ArtifactCore/include/IO/Image/ImageExporter.ixx',
    'ArtifactCore/include/UI/LayoutState.ixx',
    'ArtifactCore/include/Media/MediaReader.ixx',
    'ArtifactCore/include/Graphics/GPUInfo.ixx',
    'ArtifactCore/include/UI/ViewOrientationNavigator.ixx',
    'ArtifactCore/include/Media/MediaProbe.ixx',
    'ArtifactCore/include/IO/Image/AsyncImageWriterManager.ixx',
    'ArtifactCore/include/UI/InteractiveActions.ixx',
    'ArtifactCore/include/Test/TestHelper.ixx',
    'ArtifactCore/include/Media/MediaPlaybackController.ixx',
    'ArtifactCore/include/Graphics/GPUComputeContext.ixx',
    'ArtifactCore/include/UI/InputOperatorManager.ixx',
    'ArtifactCore/include/Test/Test.ixx',
    'ArtifactCore/include/Media/MediaMetaData.ixx',
    'ArtifactCore/include/Graphics/GLMHelper.ixx',
    'ArtifactCore/include/UI/StandardActions.ixx',
    'ArtifactCore/include/Media/MediaInfo.ixx',
    'ArtifactCore/include/UI/InputOperator.ixx',
    'ArtifactCore/include/Graphics/MotionBlur.ixx',
    'ArtifactCore/include/Media/MediaImageFrameDecoder.ixx',
    'ArtifactCore/include/UI/InputEvent.ixx',
    'ArtifactCore/include/IO/asio_async_file_writer.ixx',
    'ArtifactCore/include/Graphics/LayerBlendCS_PSO_Helper.ixx',
    'ArtifactCore/include/Media/MediaFrame.ixx',
    'ArtifactCore/include/UI/SelectionManager.ixx',
    'ArtifactCore/include/Graphics/Shader/BasicGeometryShader.ixx',
    'ArtifactCore/include/UI/RotoMaskEditor.ixx',
    'ArtifactCore/include/Source/ISource.ixx',
    'ArtifactCore/include/Media/MediaEditorController.ixx',
    'ArtifactCore/include/Graphics/Texture/TextureManager.ixx',
    'ArtifactCore/include/Utils/HashValue.ixx',
    'ArtifactCore/include/Media/MediaAudioDecoder.ixx',
    'ArtifactCore/include/Utils/JsonLike.ixx',
    'ArtifactCore/include/Utils/ImageInfoLike.ixx',
    'ArtifactCore/include/Media/ISource.ixx',
    'ArtifactCore/include/Media/ImageSequenceSource.ixx',
    'ArtifactCore/include/Utils/Id.ixx',
    'ArtifactCore/include/Icon/SvgToIcon.ixx',
    'ArtifactCore/include/Utils/AssetFingerprint.ixx',
    'ArtifactCore/include/Utils/MultipleTag.ixx',
    'ArtifactCore/include/Utils/Localization.ixx',
    'ArtifactCore/include/Graphics/Shader/Vertex/BasicVertexShader.ixx',
    'ArtifactCore/include/Utils/Path.ixx',
    'ArtifactCore/include/Transform/StaticTransform2D.ixx',
    'ArtifactCore/include/ImageProcessing/AbstractImageGenerator.ixx',
    'ArtifactCore/include/Utils/ScopedTimer.ixx',
    'ArtifactCore/include/Transform/Scale2D.ixx',
    'ArtifactCore/include/Shape/ShapeTypes.ixx',
    'ArtifactCore/include/Utils/String.ixx',
    'ArtifactCore/include/Image/BitmapImage.ixx',
    'ArtifactCore/include/Utils/StringConvertor.ixx',
    'ArtifactCore/include/Shape/ShapePath.ixx',
    'ArtifactCore/include/Image/CompressQuality.ixx',
    'ArtifactCore/include/Utils/SizeLike.ixx',
    'ArtifactCore/include/Transform/Rotate.ixx',
    'ArtifactCore/include/Utils/StringLike.ixx',
    'ArtifactCore/include/Shape/ShapeLayer.ixx',
    'ArtifactCore/include/Image/CvMatPaintEngine.ixx',
    'ArtifactCore/include/Utils/Tag.ixx',
    'ArtifactCore/include/Shape/ShapeGroup.ixx',
    'ArtifactCore/include/Image/Export/ImageExportOptions.ixx',
    'ArtifactCore/include/Math/InterpolatorFactory.ixx',
    'ArtifactCore/include/Graphics/Shader/HLSL/GraphicsHelper.ixx',
    'ArtifactCore/include/Tracking/MotionTracker.ixx',
    'ArtifactCore/include/Graphics/Shader/HLSL/GradientShader.ixx',
    'ArtifactCore/include/Utils/WindowStyleCSS.ixx',
    'ArtifactCore/include/Image/ImageF32x4_With_Cache.ixx',
    'ArtifactCore/include/Graphics/Shader/HLSL/ColorCorrectionShaders.ixx',
    'ArtifactCore/include/Image/Helper/ImageFormatHelper.ixx',
    'ArtifactCore/include/Material/Material.ixx',
    'ArtifactCore/include/Image/ImageF32x4_RGBA.ixx',
    'ArtifactCore/include/Utils/VectorLike.ixx',
    'ArtifactCore/include/Image/ImageYUV420.ixx',
    'ArtifactCore/include/Image/ImageUtils.ixx',
    'ArtifactCore/include/Graphics/Shader/HLSL/BlurShaders.ixx',
    'ArtifactCore/include/ImageProcessing/SolidColorGenerator.ixx',
    'ArtifactCore/include/Mask/RotoMask.ixx',
    'ArtifactCore/include/Utils/UniString.ixx',
    'ArtifactCore/include/Geometry/CameraGuide.ixx',
    'ArtifactCore/include/Image/PSDDocument.ixx',
    'ArtifactCore/include/Graphics/Shader/HLSL/BasicShaders.ixx',
    'ArtifactCore/include/Geometry/CalcSafeArea.ixx',
    'ArtifactCore/include/Image/RawImage.ixx',
    'ArtifactCore/include/ImageProcessing/SharpenDirectionalBlur.ixx',
    'ArtifactCore/include/Geometry/CalcGrid.ixx',
    'ArtifactCore/include/Image/Sarturation.ixx',
    'ArtifactCore/include/Geometry/BezierPathSampler.ixx',
    'ArtifactCore/include/Geometry/BezierCalculator.ixx',
    'ArtifactCore/include/Layer/LayerBlend.ixx',
    'ArtifactCore/include/Geometry/MeshImporter.ixx',
    'ArtifactCore/include/Geometry/Fracture.ixx',
    'ArtifactCore/include/Geometry/MeshEdgeExtractor.ixx',
    'ArtifactCore/include/Geometry/LayerBoundsCalculator.ixx',
    'ArtifactCore/include/Layer/LayerMatte.ixx',
    'ArtifactCore/include/Geometry/LayerAlignment.ixx',
    'ArtifactCore/include/Graphics/Shader/Compute/MaskCutoutPipeline.ixx',
    'ArtifactCore/include/Graphics/Shader/Compute/LayerBlendComputeShader.ixx',
    'ArtifactCore/include/ImageProcessing/DirectCompute/GlowCS.ixx',
    'ArtifactCore/include/Graphics/Shader/Compute/HLSL/MaskCutout.ixx',
    'ArtifactCore/include/ImageProcessing/OpenCV/FaceDetectionEngine.ixx',
    'ArtifactCore/include/ImageProcessing/OpenCV/CvUtils.ixx',
    'ArtifactCore/include/ImageProcessing/DirectCompute/NegateCS.ixx',
    'ArtifactCore/include/ImageProcessing/ColorTransform/LevelsCurves.ixx',
    'ArtifactCore/include/ImageProcessing/OpenCV/FaceTracker.ixx',
    'ArtifactCore/include/ImageProcessing/OpenCV/G-API/GPUInfoOld.ixx',
    'ArtifactCore/include/Script/Engine/Func/BuiltinManager.ixx',
    'ArtifactCore/include/Script/Engine/Value/Lexer.ixx',
    'ArtifactCore/include/Script/Engine/Syntax/ASTNode.ixx',
    'ArtifactCore/include/Scene/SimulationSettings.ixx',
    'ArtifactCore/include/Scene/SceneNode.ixx',
]

base = r'X:\dev\artifactstudio'
modified = []
skipped_missing = []
no_change_needed = []

EXPORT_MODULE_PATTERN = re.compile(r'^export\s+module\s+')

for rel_path in files:
    full_path = os.path.join(base, rel_path.replace('/', os.sep))
    if not os.path.exists(full_path):
        skipped_missing.append(rel_path)
        continue

    with open(full_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Find export module line index
    export_idx = None
    for i, line in enumerate(lines):
        if EXPORT_MODULE_PATTERN.match(line.strip()):
            export_idx = i
            break

    if export_idx is None:
        no_change_needed.append((rel_path, 'no export module line'))
        continue

    # Find Qt includes BEFORE export module
    qt_before = []
    for i in range(export_idx):
        if QT_PATTERN.match(lines[i]):
            qt_before.append(i)

    if not qt_before:
        no_change_needed.append((rel_path, 'no Qt includes before export module'))
        continue

    # Build new lines: remove Qt includes from before export module, insert after
    moved_lines = [lines[i] for i in qt_before]
    qt_before_set = set(qt_before)
    new_lines = []
    for i, line in enumerate(lines):
        if i in qt_before_set:
            continue  # skip - will be moved
        new_lines.append(line)
        if i == export_idx:
            # Insert moved Qt includes right after export module line
            new_lines.extend(moved_lines)

    with open(full_path, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    modified.append((rel_path, [lines[i].strip() for i in qt_before]))

print(f'Total files in list: {len(files)}')
print(f'Files not found on disk: {len(skipped_missing)}')
print(f'Files with no changes needed: {len(no_change_needed)}')
print(f'Files modified: {len(modified)}')
print()
for path, includes in modified:
    print(f'MODIFIED: {path}')
    for inc in includes:
        print(f'  moved: {inc}')
